"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var addon = require('./build/release/addon');
exports.sgetrf = addon.sgetrf;
exports.dgetrf = addon.dgetrf;
exports.sgbtrf = addon.sgbtrf;
exports.dgbtrf = addon.dgbtrf;
exports.sgttrf = addon.sgttrf;
exports.dgttrf = addon.dgttrf;
exports.spotrf = addon.spotrf;
exports.dpotrf = addon.dpotrf;
exports.spstrf = addon.spstrf;
exports.dpstrf = addon.dpstrf;
exports.spftrf = addon.spftrf;
exports.dpftrf = addon.dpftrf;
exports.spptrf = addon.spptrf;
exports.dpptrf = addon.dpptrf;
exports.spbtrf = addon.spbtrf;
exports.dpbtrf = addon.dpbtrf;
exports.spttrf = addon.spttrf;
exports.dpttrf = addon.dpttrf;
exports.ssytrf = addon.ssytrf;
exports.dsytrf = addon.dsytrf;
exports.ssptrf = addon.ssptrf;
exports.dsptrf = addon.dsptrf;
